apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      name: todo-pod
      labels:
        app: todo
    spec: 
     containers:
     - name: todo
       image: quay.io/abhay3802/todo-list:0.0.2
       imagePullPolicy: IfNotPresent
       ports: 
       - containerPort: 3000
       resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
     imagePullSecrets:
        - name: quay-creds
     securityContext:
        runAsGroup: 0
        runAsUser: 0

